### ISSUE TITLE
Select which error levels to report

### ISSUE THREAD

**Issue by jlai79** [Pieter-Veenstra/ULS-Monitor#1]
Hello Pieter,

I just tried out ULS Monitor and got lots of mails. Is it possible to specify that (for example) "verbose" lines in the log are not added to the list and not sent my mail?

JL

**Comment by Pieter-Veenstra** [comment]
Hi JL,

Yes you can configure all the emails that you want to be ignored. As part of the installation you should have created the Actions list. Within the action list you can include the whole message or part of a message that you want to be ignored. So for example  if your logs included a message "Something has gone wrong at url http://whatever url" Then you could include the first part of the message so that the message is ignored for any url. This is especially useful when thee are GUID included in the message.
